name: CocaCola
main: Acke\CocaCola\CocaCola
version: 1.0.1
api: "1.13.0"
author:
  - Acke
commands:
  cocacola:
    aliases:
      - cc
    description: "Thirst stops here... Have a Coke. Get health and food or die of deliciousness overload."
    permission: cocacola.command.cocacola
    usage: /cocacola
permissions:
  cocacola:
    default: true
    description: "Allows access of all CocaCola features"
    children:
      cocacola.command:
        default: true
        description: "Allows usage of all CocaCola commands"
        children:
          cocacola.command.cocacola:
            default: true
            description: "Allows usage of /cocacola"
